# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Job',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
