# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-04 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190304_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
